// Curated list of common, easy-to-spell English words (4-8 letters) for
// memorable password generation. ~400 words gives solid entropy per word.
const words = [
  'able','acid','aged','also','area','army','away','baby','back','ball',
  'band','bank','base','bath','bean','bear','beat','been','beer','bell',
  'belt','best','bill','bird','bite','blow','blue','boat','body','bomb',
  'bond','bone','book','boom','born','boss','both','bowl','bulk','burn',
  'bush','busy','cake','call','calm','came','camp','card','care','case',
  'cash','cast','cave','chip','city','claim','clay','clip','club','clue',
  'coal','coat','code','coin','cold','come','cook','cool','cope','copy',
  'core','cost','crew','crop','dare','dark','data','date','dawn','dead',
  'deal','dear','debt','deep','deer','deny','desk','diet','dirt','disk',
  'dock','does','done','door','dose','down','drag','draw','drew','drop',
  'drug','drum','dual','duke','dull','dump','dust','duty','each','earn',
  'ease','east','easy','edge','else','even','ever','evil','exam','exit',
  'face','fact','fail','fair','fall','fame','farm','fast','fate','fear',
  'feed','feel','feet','fell','felt','file','fill','film','find','fine',
  'fire','firm','fish','flag','flat','fled','flew','flip','flow','foam',
  'fold','folk','food','fool','foot','ford','form','fort','foul','four',
  'free','from','fuel','full','fund','fury','fuse','gain','game','gang',
  'gate','gave','gear','gene','gift','girl','give','glad','glow','glue',
  'goal','goes','gold','golf','gone','good','grab','gray','grew','grid',
  'grip','grow','gulf','guru','hair','half','hall','halt','hand','hang',
  'hard','harm','hate','have','head','heal','heap','hear','heat','held',
  'hell','help','herb','here','hero','hide','high','hill','hint','hire',
  'hold','hole','holy','home','hook','hope','horn','host','hour','huge',
  'hung','hunt','hurt','idea','inch','into','iron','item','jack','jail',
  'jane','jean','jobs','john','join','joke','jump','june','jury','just',
  'keen','keep','kent','kept','kick','kill','kind','king','knee','knew',
  'knit','knot','know','lack','laid','lake','lamp','land','lane','last',
  'late','lawn','lead','leaf','lean','left','lend','less','life','lift',
  'like','limb','lime','line','link','lion','list','live','load','loan',
  'lock','logo','long','look','lord','lose','loss','lost','love','luck',
  'made','mail','main','make','male','mall','many','mark','mask','mass',
  'mate','mayo','maze','meal','mean','meat','meet','melt','memo','menu',
  'mere','mesh','mild','mile','milk','mill','mind','mine','mint','miss',
  'mode','mood','moon','more','most','move','much','must','myth','name',
  'navy','near','neat','neck','need','nest','news','next','nice','nine',
  'node','none','norm','nose','note','noun','nude','nuts','odds','once',
  'only','onto','open','oral','oven','over','pace','pack','page','paid',
  'pain','pair','pale','palm','panel','park','part','pass','past','path',
  'peak','peer','pick','pile','pine','pink','pipe','plan','play','plot',
  'plug','plus','poem','poet','poll','polo','pond','pool','poor','pope',
  'port','pose','post','pour','pray','pull','pump','pure','push','quit',
];

export default words;
